name: configsuite-tui

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      TERM: linux
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/requirements.txt
        pip install -r requirements/test-requirements.txt
    - name: Tests
      run: |
        coverage run --source='.' -m unittest discover
    - run: black --check --verbose --diff .
    - run: flake8
    - run: pylint configsuite_tui

      



